/**
 * タスクカード(21枚)
 * 各スロットに「堅い道(長いが低リスク)」「安い道(短いが高リスク)」の2枚 + 中間 2〜3枚。
 *
 * phase        = 候補プールに補充されるフェーズ
 * estimate     = 見積工数(公開情報。実工数は risk 別分布で振れる。RULES.md §2-2)
 * risk         = 見積の不確実性(低=振れ幅小 / 高=上振れしやすい)
 * maxLevel     = 上限Lv(1 = 積み増しによる Lv2 納品は不可)
 * prerequisiteSlots = 前提成果物(納品済みでないと着手できない。RULES.md §6-1)
 *
 * 依存の連鎖:
 *   要件定義書 → サイトマップ → ワイヤーフレーム → デザインカンプ → トップ / 下層 → テスト・公開
 *                          ↘ CMS              ↘ スタイルガイド
 */
import type { TaskCard } from '../types/content'

export const TASKS: TaskCard[] = [
  // ═══ フェーズ1: 企画・要件定義 ═══
  // 要件定義書(requirements) — 起点。前提なし
  {
    id: 't-req-heavy',
    name: 'フルヒアリング・要件定義',
    phase: 1,
    slot: 'requirements',
    skill: 'direction',
    estimate: 5,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: [],
  },
  {
    id: 't-req-light',
    name: 'シンプル要件確認',
    phase: 1,
    slot: 'requirements',
    skill: 'direction',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: [],
  },
  // サイトマップ(sitemap) — 要件定義書が必要
  {
    id: 't-sitemap-heavy',
    name: '複雑ナビゲーション設計',
    phase: 1,
    slot: 'sitemap',
    skill: 'direction',
    estimate: 4,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['requirements'],
  },
  {
    id: 't-sitemap-light',
    name: 'シンプルサイト構成',
    phase: 1,
    slot: 'sitemap',
    skill: 'direction',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['requirements'],
  },
  {
    id: 't-sitemap-mid',
    name: '標準的なマップ作成',
    phase: 1,
    slot: 'sitemap',
    skill: 'direction',
    estimate: 3,
    risk: 'medium',
    maxLevel: 2,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['requirements'],
  },

  // ═══ フェーズ2: 設計・デザイン ═══
  // ワイヤーフレーム(wireframe) — サイトマップが必要
  {
    id: 't-wireframe-heavy',
    name: 'ハイフィ・インタラクション設計',
    phase: 2,
    slot: 'wireframe',
    skill: 'design',
    estimate: 4,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['sitemap'],
  },
  {
    id: 't-wireframe-light',
    name: 'シンプルワイヤー',
    phase: 2,
    slot: 'wireframe',
    skill: 'design',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['sitemap'],
  },
  // デザインカンプ(design-comp) — ワイヤーフレームが必要
  {
    id: 't-design-heavy',
    name: 'フルオーダーデザイン',
    phase: 2,
    slot: 'design-comp',
    skill: 'design',
    estimate: 5,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['wireframe'],
  },
  {
    id: 't-design-light',
    name: '既製テーマカスタマイズ',
    phase: 2,
    slot: 'design-comp',
    skill: 'design',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['wireframe'],
  },
  {
    id: 't-design-mid',
    name: 'テンプレート カスタム',
    phase: 2,
    slot: 'design-comp',
    skill: 'design',
    estimate: 3,
    risk: 'medium',
    maxLevel: 2,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['wireframe'],
  },
  // スタイルガイド(styleguide) — ワイヤーフレームが必要
  {
    id: 't-guide-heavy',
    name: 'デザインシステム構築',
    phase: 2,
    slot: 'styleguide',
    skill: 'design',
    estimate: 4,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['wireframe'],
  },
  {
    id: 't-guide-light',
    name: 'スタイル基本セット',
    phase: 2,
    slot: 'styleguide',
    skill: 'design',
    estimate: 2,
    risk: 'medium',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['wireframe'],
  },

  // ═══ フェーズ3: 開発 ═══
  // トップページ(top-page) — デザインカンプが必要
  {
    id: 't-top-heavy',
    name: 'トップページ完全カスタム',
    phase: 3,
    slot: 'top-page',
    skill: 'engineering',
    estimate: 5,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['design-comp'],
  },
  {
    id: 't-top-light',
    name: 'トップページ スクラッチ',
    phase: 3,
    slot: 'top-page',
    skill: 'engineering',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['design-comp'],
  },
  // 下層ページ(sub-pages) — デザインカンプが必要
  {
    id: 't-sub-heavy',
    name: '下層ページ 豊富オーダー',
    phase: 3,
    slot: 'sub-pages',
    skill: 'engineering',
    estimate: 4,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['design-comp'],
  },
  {
    id: 't-sub-light',
    name: 'テンプレート流用',
    phase: 3,
    slot: 'sub-pages',
    skill: 'engineering',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['design-comp'],
  },
  // CMS(cms) — サイトマップが必要(デザインとは並行できる)
  {
    id: 't-cms-heavy',
    name: 'フル CMS 構築',
    phase: 3,
    slot: 'cms',
    skill: 'engineering',
    estimate: 5,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['sitemap'],
  },
  {
    id: 't-cms-light',
    name: 'SaaS 導入',
    phase: 3,
    slot: 'cms',
    skill: 'direction',
    estimate: 2,
    risk: 'high',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['sitemap'],
  },
  {
    id: 't-cms-mid',
    name: 'CMS 標準実装',
    phase: 3,
    slot: 'cms',
    skill: 'engineering',
    estimate: 3,
    risk: 'medium',
    maxLevel: 2,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['sitemap'],
  },

  // ═══ フェーズ4: テスト・公開 ═══
  // テスト・公開(launch) — トップページが必要
  {
    id: 't-launch-heavy',
    name: '詳細テスト・チューニング',
    phase: 4,
    slot: 'launch',
    skill: 'engineering',
    estimate: 4,
    risk: 'low',
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    prerequisiteSlots: ['top-page'],
  },
  {
    id: 't-launch-light',
    name: '動作確認・公開',
    phase: 4,
    slot: 'launch',
    skill: 'engineering',
    estimate: 2,
    risk: 'medium',
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    prerequisiteSlots: ['top-page'],
  },
]
