/**
 * プレイテスト用の仮タスクタイル(フェーズごと5枚 × 4フェーズ)
 * フレーバーは Web 制作あるある。数値はプレイテストで調整する前提。
 */
import type { TaskTile } from '../types/content'

export const TASKS: TaskTile[] = [
  // ───── フェーズ1: 企画・要件定義 ─────
  {
    id: 'p1-hearing',
    name: 'キックオフヒアリング',
    phase: 1,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: { skill: 'direction', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p1-requirements',
    name: '要件定義書作成',
    phase: 1,
    requiredTokens: 3,
    deliverables: [2],
    skillRequirement: { skill: 'direction', level: 2 },
    hiddenRequirement: true,
    dependsOn: ['p1-hearing'],
    collaboration: false,
    eventMark: false,
    cost: 2,
    fatigue: 2,
    specialEffect: null,
  },
  {
    id: 'p1-sitemap',
    name: 'サイトマップ作成',
    phase: 1,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: null,
    hiddenRequirement: false,
    dependsOn: ['p1-hearing'],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: { type: 'NEXT_TASK_COST_DOWN', amount: 1 },
  },
  {
    id: 'p1-research',
    name: '競合サイト調査',
    phase: 1,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: null,
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: true,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p1-estimate',
    name: '見積もり提出',
    phase: 1,
    requiredTokens: 3,
    deliverables: [1, 2],
    skillRequirement: { skill: 'direction', level: 1 },
    hiddenRequirement: false,
    dependsOn: ['p1-requirements'],
    collaboration: true,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  // ───── フェーズ2: 設計・デザイン ─────
  {
    id: 'p2-wireframe',
    name: 'ワイヤーフレーム作成',
    phase: 2,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: { skill: 'design', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p2-design-comp',
    name: 'デザインカンプ作成',
    phase: 2,
    requiredTokens: 4,
    deliverables: [2, 2],
    skillRequirement: { skill: 'design', level: 2 },
    hiddenRequirement: true,
    dependsOn: ['p2-wireframe'],
    collaboration: false,
    eventMark: false,
    cost: 2,
    fatigue: 2,
    specialEffect: null,
  },
  {
    id: 'p2-client-wait',
    name: '先方確認待ち',
    phase: 2,
    requiredTokens: 1,
    deliverables: [],
    skillRequirement: null,
    hiddenRequirement: false,
    dependsOn: ['p2-wireframe'],
    collaboration: false,
    eventMark: true,
    cost: 0,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p2-styleguide',
    name: 'スタイルガイド作成',
    phase: 2,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: { skill: 'design', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: { type: 'NEXT_TASK_COST_DOWN', amount: 1 },
  },
  {
    id: 'p2-prototype',
    name: 'プロトタイプレビュー',
    phase: 2,
    requiredTokens: 3,
    deliverables: [2],
    skillRequirement: { skill: 'direction', level: 1 },
    hiddenRequirement: false,
    dependsOn: ['p2-design-comp'],
    collaboration: true,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  // ───── フェーズ3: 開発 ─────
  {
    id: 'p3-env',
    name: '開発環境構築',
    phase: 3,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: { skill: 'engineering', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p3-top',
    name: 'トップページ実装',
    phase: 3,
    requiredTokens: 3,
    deliverables: [2],
    skillRequirement: { skill: 'engineering', level: 2 },
    hiddenRequirement: true,
    dependsOn: ['p3-env'],
    collaboration: false,
    eventMark: false,
    cost: 2,
    fatigue: 2,
    specialEffect: null,
  },
  {
    id: 'p3-pages',
    name: '下層ページ実装',
    phase: 3,
    requiredTokens: 4,
    deliverables: [1, 1],
    skillRequirement: { skill: 'engineering', level: 1 },
    hiddenRequirement: false,
    dependsOn: ['p3-env'],
    collaboration: true,
    eventMark: false,
    cost: 2,
    fatigue: 2,
    specialEffect: null,
  },
  {
    id: 'p3-cms',
    name: 'CMS 組み込み',
    phase: 3,
    requiredTokens: 3,
    deliverables: [2],
    skillRequirement: { skill: 'engineering', level: 2 },
    hiddenRequirement: true,
    dependsOn: ['p3-top'],
    collaboration: false,
    eventMark: true,
    cost: 2,
    fatigue: 2,
    specialEffect: null,
  },
  {
    id: 'p3-animation',
    name: 'アニメーション実装',
    phase: 3,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: { skill: 'design', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  // ───── フェーズ4: テスト ─────
  {
    id: 'p4-device',
    name: '実機検証',
    phase: 4,
    requiredTokens: 3,
    deliverables: [2],
    skillRequirement: { skill: 'engineering', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: true,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p4-crossbrowser',
    name: 'クロスブラウザ対応',
    phase: 4,
    requiredTokens: 3,
    deliverables: [1],
    skillRequirement: { skill: 'engineering', level: 2 },
    hiddenRequirement: true,
    dependsOn: ['p4-device'],
    collaboration: false,
    eventMark: true,
    cost: 2,
    fatigue: 2,
    specialEffect: null,
  },
  {
    id: 'p4-performance',
    name: '表示速度改善',
    phase: 4,
    requiredTokens: 2,
    deliverables: [2],
    skillRequirement: { skill: 'engineering', level: 1 },
    hiddenRequirement: false,
    dependsOn: [],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: null,
  },
  {
    id: 'p4-client-review',
    name: '先方レビュー対応',
    phase: 4,
    requiredTokens: 2,
    deliverables: [1],
    skillRequirement: { skill: 'direction', level: 1 },
    hiddenRequirement: false,
    dependsOn: ['p4-device'],
    collaboration: false,
    eventMark: false,
    cost: 1,
    fatigue: 1,
    specialEffect: { type: 'NEXT_TASK_COST_DOWN', amount: 1 },
  },
  {
    id: 'p4-launch',
    name: '公開作業',
    phase: 4,
    requiredTokens: 3,
    deliverables: [2],
    skillRequirement: { skill: 'engineering', level: 1 },
    hiddenRequirement: false,
    dependsOn: ['p4-client-review'],
    collaboration: true,
    eventMark: false,
    cost: 1,
    fatigue: 2,
    specialEffect: null,
  },
]
