/**
 * タスクカード(約20枚)
 * 各スロット(9個)に「堅い道」「安い道」の2枚 + 中間・バリエーション2-3枚
 * phase=公開フェーズ / lane=配置可能列 / skill=系統 / effort=必要工数 / maxLevel=上限Lv
 */
import type { TaskCard } from '../types/content'

export const TASKS: TaskCard[] = [
  // ═══ フェーズ1: 企画・要件定義 ═══
  // 要件定義書(requirements) — phase 1
  {
    id: 't-req-heavy',
    name: 'フルヒアリング・要件定義',
    phase: 1,
    slot: 'requirements',
    skill: 'direction',
    effort: 5,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'start',
  },
  {
    id: 't-req-light',
    name: 'シンプル要件確認',
    phase: 1,
    slot: 'requirements',
    skill: 'direction',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'start',
  },
  // サイトマップ(sitemap) — phase 1
  {
    id: 't-sitemap-heavy',
    name: '複雑ナビゲーション設計',
    phase: 1,
    slot: 'sitemap',
    skill: 'direction',
    effort: 4,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'start',
  },
  {
    id: 't-sitemap-light',
    name: 'シンプルサイト構成',
    phase: 1,
    slot: 'sitemap',
    skill: 'direction',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'start',
  },
  {
    id: 't-sitemap-mid',
    name: '標準的なマップ作成',
    phase: 1,
    slot: 'sitemap',
    skill: 'direction',
    effort: 3,
    maxLevel: 2,
    fatigue: 1,
    cost: 1,
    lane: 'start',
  },
  // ═══ フェーズ2: 設計・デザイン ═══
  // ワイヤーフレーム(wireframe) — phase 2
  {
    id: 't-wireframe-heavy',
    name: 'ハイフィ・インタラクション設計',
    phase: 2,
    slot: 'wireframe',
    skill: 'design',
    effort: 4,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'start',
  },
  {
    id: 't-wireframe-light',
    name: 'シンプルワイヤー',
    phase: 2,
    slot: 'wireframe',
    skill: 'design',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'start',
  },
  // デザインカンプ(design-comp) — phase 2
  {
    id: 't-design-heavy',
    name: 'フルオーダーデザイン',
    phase: 2,
    slot: 'design-comp',
    skill: 'design',
    effort: 5,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'middle',
  },
  {
    id: 't-design-light',
    name: '既製テーマカスタマイズ',
    phase: 2,
    slot: 'design-comp',
    skill: 'design',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  {
    id: 't-design-mid',
    name: 'テンプレーション カスタム',
    phase: 2,
    slot: 'design-comp',
    skill: 'design',
    effort: 3,
    maxLevel: 2,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  // スタイルガイド(styleguide) — phase 2
  {
    id: 't-guide-heavy',
    name: 'デザインシステム構築',
    phase: 2,
    slot: 'styleguide',
    skill: 'design',
    effort: 4,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'middle',
  },
  {
    id: 't-guide-light',
    name: 'スタイル基本セット',
    phase: 2,
    slot: 'styleguide',
    skill: 'design',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  // ═══ フェーズ3: 開発 ═══
  // トップページ(top-page) — phase 3
  {
    id: 't-top-heavy',
    name: 'トップページ完全カスタム',
    phase: 3,
    slot: 'top-page',
    skill: 'engineering',
    effort: 5,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'middle',
  },
  {
    id: 't-top-light',
    name: 'トップページスクラッチ',
    phase: 3,
    slot: 'top-page',
    skill: 'engineering',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  // 下層ページ(sub-pages) — phase 3
  {
    id: 't-sub-heavy',
    name: '下層ページ豊富オーダー',
    phase: 3,
    slot: 'sub-pages',
    skill: 'engineering',
    effort: 4,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'middle',
  },
  {
    id: 't-sub-light',
    name: 'テンプレート流用',
    phase: 3,
    slot: 'sub-pages',
    skill: 'engineering',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  // CMS(cms) — phase 3
  {
    id: 't-cms-heavy',
    name: 'フル CMS 構築',
    phase: 3,
    slot: 'cms',
    skill: 'engineering',
    effort: 5,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'middle',
  },
  {
    id: 't-cms-light',
    name: 'SaaS 導入',
    phase: 3,
    slot: 'cms',
    skill: 'direction',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  {
    id: 't-cms-mid',
    name: 'CMS 標準実装',
    phase: 3,
    slot: 'cms',
    skill: 'engineering',
    effort: 3,
    maxLevel: 2,
    fatigue: 1,
    cost: 1,
    lane: 'middle',
  },
  // ═══ フェーズ4: テスト・公開 ═══
  // テスト・公開(launch) — phase 4
  {
    id: 't-launch-heavy',
    name: '詳細テスト・チューニング',
    phase: 4,
    slot: 'launch',
    skill: 'engineering',
    effort: 4,
    maxLevel: 2,
    fatigue: 2,
    cost: 2,
    lane: 'finish',
  },
  {
    id: 't-launch-light',
    name: '動作確認・公開',
    phase: 4,
    slot: 'launch',
    skill: 'engineering',
    effort: 2,
    maxLevel: 1,
    fatigue: 1,
    cost: 1,
    lane: 'finish',
  },
]
